### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by jetheurer** [propertone/craigslist-renew#1]
Hi, I noticed a log in error.  Is there a way to get around this?
$ perl craigslist-renew.pl config.yml 
Error GETing https://accounts.craigslist.org/login: Status read failed: Connection reset by peer at craigslist-renew.pl line 32

Interestingly I've noticed the same issue with this repo: https://github.com/Sepero/CraigsRenewer/issues/1

**Comment by propertone** [comment]
I haven't been able to reproduce this. Are you still getting this error?

**Comment by irealva** [comment]
I had got a slightly different error but it referenced the same line in the code. I installed the Mozilla::CA module and it worked fine. 

Got the suggestion from this page: http://www.jwz.org/blog/2014/03/apple-broke-lwp-in-a-new-and-exciting-way-on-10-9-2/
"This problem can be fixed by either setting the PERL_LWP_SSL_CA_FILE
envirionment variable or by installing the Mozilla::CA module.

To disable verification of SSL peers set the PERL_LWP_SSL_VERIFY_HOSTNAME
envirionment variable to 0. If you do this you can't be sure that you
communicate with the expected peer."

**Comment by propertone** [comment]
Thanks for the tip. As this issue is unrelated to the project, I'll go ahead and close this request.
